@startsalt
title 管理画面
scale 2
{+
  ---
  ^部署選択^
  {SI
    {#
      No.|部署|分類|文書番号|作成者|訂符|更新日時|文書名|ファイル
      1|第一課|電気|A社-第一課-電気-001|○○太郎|NC|2021/12/10|○○について|A社-第一課-電気-001_NC_○○について.pdf
      2|第一課|電子|A社-第一課-電子-001|□□次郎|A|2022/1/1|基礎の□□|A社-第一課-電子-001_A_基礎の□□.pdf
      3|第二課|電気|A社-第二課-電気-001|△△三郎|NC|2021/12/22|△△について|A社-第二課-電気-001_NC_△△について.pdf
      4|第二課|電気|A社-第二課-電気-002|✕✕花子|NC|2022/1/10|初歩の△△|A社-第二課-電気-002_NC_初歩の△△.pdf
    }
  }
  [番号予約]
  [新規登録]
  [更新/改訂]
}
@endsalt